Fix troublesome RateLimit lock implementation
After switching to anyio you could get a `AttributeError: 'RateLimit' object has no attribute '_waiters'`

This has now been completely circumvented by not subclassing anyio.Lock directly.